name: exchangerates
description: Flutter application for tracking exchange rate prices.

publish_to: "none"
#* Flutter v3.7.0

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flash: ^2.0.5
  shimmer: ^3.0.0
  chopper: ^6.1.3
  equatable: ^2.0.5
  fl_chart: ^0.62.0
  flutter_svg: ^1.1.6
  app_settings: ^4.2.0
  circle_flags: ^1.0.3
  country_flags: ^1.0.0
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  flutter_animate: ^4.1.1+1
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.1.1

  get_it: ^7.2.0
  rxdart: ^0.27.7
  provider: ^6.0.4
  injectable: ^2.1.0

  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

  redux: ^5.0.0

  location: ^4.4.0
  google_maps_flutter: ^2.2.8
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0

dev_dependencies:
  copy_with_extension_gen: ^5.0.2
  injectable_generator: ^2.1.3
  chopper_generator: ^6.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/common/

    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/Circular_Std_Regular.ttf
          weight: 400
        - asset: assets/fonts/Circular_Std_Medium.ttf
          weight: 500
        - asset: assets/fonts/Circular_Std_Bold.ttf
          weight: 700
